# Generated by Django 4.1.8 on 2023-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('slogan', models.CharField(max_length=200)),
                ('head_quaters', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('established', models.CharField(max_length=200)),
            ],
        ),
    ]
