# Generated by Django 4.1.8 on 2023-04-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='established',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='head_quaters',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='website',
        ),
    ]
