# Generated by Django 3.2.12 on 2023-06-20 18:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField()),
                ('no_seats', models.IntegerField(default=0)),
                ('arrival_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_to', to='Airplanes.airport')),
                ('departure_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_from', to='Airplanes.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(200)])),
                ('description', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(200)])),
                ('descrption', models.TextField()),
                ('working_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airplanes.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=9)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airplanes.flight')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airplanes.profile')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airplanes.plane'),
        ),
    ]
