# Generated by Django 3.2.12 on 2023-06-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Airplanes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='surname',
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
