# Generated by Django 3.2.12 on 2023-06-20 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Airplanes', '0002_auto_20230620_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passenger',
            new_name='Profile',
        ),
    ]
